
#pragma once
#include "Parameters.h"

namespace MODUTILS{

*MODPARAMS::NVECTOR MODUTILS::MAKE_NVEC(double flat_C[MODPARAMS::N]);
*MODPARAMS::NVECTOR MODUTILS::MAKE_NVEC(double C[MODPARAMS::NX][MODPARAMS::NY][MODPARAMS::NZ]);

};
